tests:
  image: python:3.9
  script:
    - pip install flake8 mypy coverage pytest interrogate numpy
    - pip install -e .
    - coverage run --source=myqueue -m pytest -v
    - coverage report -i --fail-under=81
    - mypy -p myqueue
    - flake8 myqueue
    - interrogate -v -m -i -f 43.2 myqueue -e myqueue/test
