tests:
  image: python:3.8
  script:
    - pip install flake8 mypy coverage pytest interrogate
    - pip install -e .
    - coverage run --source=myqueue -m pytest -v
    - coverage report -i --fail-under=79
    - mypy -p myqueue
    - flake8 myqueue
    - interrogate -v -m -i -f 35.0 myqueue -e myqueue/test
