tests:
  image: python:3.6
  script:
    - pip install flake8 mypy coverage
    - pip install -e .
    - export PYTHONPATH=$PWD/myqueue/docs
    - ls $PYTHONPATH
    - coverage run -m myqueue test -v
    - coverage report -i --fail-under=68
    - mypy -p myqueue
    - flake8 myqueue
