tests:
  image: python:3.8
  script:
    - pip install flake8 mypy coverage pytest interrogate
    - pip install -e .
    - coverage run -m pytest -v
    - coverage report -i --fail-under=77
    - mypy -p myqueue
    - flake8 myqueue
    - interrogate -v -m -i -f 26.8 myqueue -e myqueue/test
