tests:
  image: python:3.9
  script:
    - python -m venv venv
    - . venv/bin/activate
    - pip install -U pip
    - pip install flake8 mypy coverage pytest interrogate numpy
    - pip install .
    - echo "import coverage; coverage.process_startup()" > venv/lib/python3.9/site-packages/cov.pth
    - touch cov.cfg
    - export COVERAGE_PROCESS_START=$PWD/cov.cfg
    - coverage run -p --source=myqueue -m pytest -v
    - coverage combine -a .coverage.*
    - coverage report -i --fail-under=86
    - mypy -p myqueue
    - flake8 myqueue
    - interrogate -v -m -i -f 49.5 myqueue -e myqueue/test

oldtests:
  image: python:3.7
  script:
    - pip install pytest numpy
    - pip install -e .
    - pytest
