tests:
  image: python:3.8
  script:
    - pip install flake8 mypy coverage pytest
    - pip install -e .
    - coverage run -m pytest
    - coverage report -i --fail-under=78
    - mypy -p myqueue
    - flake8 myqueue
