tests:
  image: python:3.9
  script:
    - pip install flake8 mypy coverage pytest interrogate numpy
    - pip install -e .
    - pwd
    - ls -ltra
    - echo $PYTHONPATH
    - echo $HOME
    - echo "import covergageeee; print()" > $PYTHONPATH/cov.pth
    - export COVERAGE_PROCESS_START=cov.cfg
    - coverage run -p --source=myqueue -m pytest -v
    - coverage combine -a .coverage.*
    - coverage report -i --fail-under=83
    - mypy -p myqueue
    - flake8 myqueue
    - interrogate -v -m -i -f 49.0 myqueue -e myqueue/test

oldtests:
  image: python:3.7
  script:
    - pip install pytest numpy
    - pip install -e .
    - pytest
