[project.urls]
homepage = "https://example.com"
repository = "https://github.com/me/spam.git"
changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"
docs = "https://readthedocs.org"
issues = "https://change/requests"
matrix = "https://mastodon/server/@me"
